// ============================================
// EXTENSION BUILD SCRIPT
// ============================================
// Reads .env, generates env/config.js, copies
// platform-specific manifests, and packages
// .zip files for Chrome, Edge, and Firefox.
// ============================================
// Usage:
//   node build.js            — builds all 3 platforms
//   node build.js chrome     — build only Chrome
//   node build.js firefox    — build only Firefox
//   node build.js edge       — build only Edge
// ============================================

const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

// ── Load .env ────────────────────────────────

function loadEnv() {
  const envPath = path.resolve(__dirname, ".env");
  if (!fs.existsSync(envPath)) {
    console.error("ERROR: .env file not found. Copy .env.example to .env and fill in values.");
    process.exit(1);
  }
  const lines = fs.readFileSync(envPath, "utf-8").split("\n");
  const env = {};
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIdx = trimmed.indexOf("=");
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const value = trimmed.slice(eqIdx + 1).trim();
    env[key] = value;
  }
  return env;
}

// ── Generate config.js ───────────────────────

function generateConfig(env) {
  const config = `// AUTO-GENERATED by build.js — do not edit manually
const ENV = Object.freeze({
  API_BASE_URL: "${env.API_BASE_URL || "https://price-tracker.gavaller.com/api/tesco"}",
  ALERTS_API_URL: "${env.ALERTS_API_URL || "https://price-tracker.gavaller.com/api/alerts"}",
  AUTH_GATEWAY_URL: "${env.AUTH_GATEWAY_URL || "https://gateway.gavaller.com"}",
  KEYCLOAK_URL: "${env.KEYCLOAK_URL || "https://auth.gavaller.com/realms/backend-ecosystem"}",
  KEYCLOAK_CLIENT_ID: "${env.KEYCLOAK_CLIENT_ID || "gateway-client"}",
  WEBSITE_URL: "${env.WEBSITE_URL || "https://price-tracker.gavaller.com"}",
});

export default ENV;
`;
  const configPath = path.resolve(__dirname, "env", "config.js");
  fs.writeFileSync(configPath, config, "utf-8");
  console.log("  ✓ env/config.js generated");
}

// ── Platform manifest generation ─────────────

function generateManifest(platform, env) {
  const base = JSON.parse(fs.readFileSync(path.resolve(__dirname, "manifest.json"), "utf-8"));

  if (platform === "firefox") {
    // Firefox uses browser_specific_settings
    base.browser_specific_settings = {
      gecko: {
        id: env.FIREFOX_EXTENSION_ID || "tesco-price-tracker@example.com",
        strict_min_version: "112.0",
      },
    };
    // Firefox MV3 uses "scripts" array for background
    base.background = { scripts: ["background/background.js"], type: "module" };
  } else {
    // Chrome / Edge use service_worker
    delete base.browser_specific_settings;
    base.background = { service_worker: "background/background.js", type: "module" };
  }

  return base;
}

// ── Package into .zip ────────────────────────

function buildPlatform(platform, env) {
  console.log(`\n── Building for ${platform.toUpperCase()} ──`);

  const distDir = path.resolve(__dirname, "dist", platform);
  if (fs.existsSync(distDir)) {
    fs.rmSync(distDir, { recursive: true });
  }
  fs.mkdirSync(distDir, { recursive: true });

  // Files/dirs to copy
  const items = [
    "env",
    "background",
    "content",
    "popup",
    "icons",
  ];

  for (const item of items) {
    const src = path.resolve(__dirname, item);
    const dest = path.resolve(distDir, item);
    if (fs.existsSync(src)) {
      copyRecursive(src, dest);
    }
  }

  // Generate platform-specific manifest
  const manifest = generateManifest(platform, env);
  fs.writeFileSync(path.resolve(distDir, "manifest.json"), JSON.stringify(manifest, null, 2));
  console.log(`  ✓ manifest.json (${platform})`);

  // Create .zip
  const zipName = `tesco-price-tracker-${platform}.zip`;
  const zipPath = path.resolve(__dirname, "dist", zipName);
  if (fs.existsSync(zipPath)) fs.unlinkSync(zipPath);

  // Use PowerShell's Compress-Archive on Windows, zip on Unix
  const isWindows = process.platform === "win32";
  if (isWindows) {
    execSync(
      `powershell -Command "Compress-Archive -Path '${distDir}\\*' -DestinationPath '${zipPath}' -Force"`,
      { stdio: "inherit" }
    );
  } else {
    execSync(`cd "${distDir}" && zip -r "${zipPath}" .`, { stdio: "inherit" });
  }
  console.log(`  ✓ ${zipName}`);
}

// ── Helpers ──────────────────────────────────

function copyRecursive(src, dest) {
  const stat = fs.statSync(src);
  if (stat.isDirectory()) {
    fs.mkdirSync(dest, { recursive: true });
    for (const child of fs.readdirSync(src)) {
      copyRecursive(path.join(src, child), path.join(dest, child));
    }
  } else {
    fs.copyFileSync(src, dest);
  }
}

// ── Main ─────────────────────────────────────

function main() {
  const args = process.argv.slice(2);
  const platforms = args.length ? args : ["chrome", "edge", "firefox"];

  console.log("Tesco Price Tracker — Extension Build");
  console.log("─".repeat(40));

  const env = loadEnv();
  generateConfig(env);

  for (const platform of platforms) {
    if (!["chrome", "edge", "firefox"].includes(platform)) {
      console.warn(`  ⚠ Unknown platform: ${platform}, skipping`);
      continue;
    }
    buildPlatform(platform, env);
  }

  console.log("\n✓ Build complete!");
  console.log(`  Output: ${path.resolve(__dirname, "dist")}`);
}

main();
