// ============================================
// EXTENSION BUILD SCRIPT
// ============================================
// Reads .env, generates env/config.js, copies
// platform-specific manifests, and packages
// .zip files for Chrome, Edge, and Firefox.
// ============================================
// Usage:
//   node build.js            — builds all 3 platforms
//   node build.js chrome     — build only Chrome
//   node build.js firefox    — build only Firefox
//   node build.js edge       — build only Edge
// ============================================

const fs = require("fs");
const path = require("path");
const zlib = require("zlib");

// ── CRC-32 (needed for ZIP) ──────────────────

const CRC_TABLE = (() => {
  const t = new Uint32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = (c & 1) ? (0xedb88320 ^ (c >>> 1)) : (c >>> 1);
    t[n] = c;
  }
  return t;
})();

function crc32(buf) {
  let c = 0xffffffff;
  for (let i = 0; i < buf.length; i++) c = CRC_TABLE[(c ^ buf[i]) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

// ── Pure-Node ZIP writer (always forward-slash paths) ──

function createZip(sourceDir, zipPath) {
  const localBlocks = [];
  const centralDir  = [];
  let offset = 0;

  function walk(dir, base) {
    for (const name of fs.readdirSync(dir).sort()) {
      const full      = path.join(dir, name);
      const entryPath = base ? `${base}/${name}` : name;   // ← always forward slash
      if (fs.statSync(full).isDirectory()) {
        walk(full, entryPath);
      } else {
        const raw        = fs.readFileSync(full);
        const deflated   = zlib.deflateRawSync(raw, { level: 9 });
        const useDeflate = deflated.length < raw.length;
        const fileData   = useDeflate ? deflated : raw;
        const method     = useDeflate ? 8 : 0;
        const crc        = crc32(raw);
        const nameBytes  = Buffer.from(entryPath, "utf8");

        // Local file header (30 bytes + name)
        const lh = Buffer.alloc(30 + nameBytes.length);
        lh.writeUInt32LE(0x04034b50, 0);
        lh.writeUInt16LE(20,         4);
        lh.writeUInt16LE(0x0800,     6);   // UTF-8 flag
        lh.writeUInt16LE(method,     8);
        lh.writeUInt16LE(0,         10);
        lh.writeUInt16LE(0,         12);
        lh.writeUInt32LE(crc,       14);
        lh.writeUInt32LE(fileData.length, 18);
        lh.writeUInt32LE(raw.length,      22);
        lh.writeUInt16LE(nameBytes.length, 26);
        lh.writeUInt16LE(0,         28);
        nameBytes.copy(lh, 30);

        localBlocks.push(lh, fileData);

        // Central directory entry (46 bytes + name)
        const cd = Buffer.alloc(46 + nameBytes.length);
        cd.writeUInt32LE(0x02014b50,  0);
        cd.writeUInt16LE(20,          4);
        cd.writeUInt16LE(20,          6);
        cd.writeUInt16LE(0x0800,      8);
        cd.writeUInt16LE(method,     10);
        cd.writeUInt16LE(0,          12);
        cd.writeUInt16LE(0,          14);
        cd.writeUInt32LE(crc,        16);
        cd.writeUInt32LE(fileData.length, 20);
        cd.writeUInt32LE(raw.length,      24);
        cd.writeUInt16LE(nameBytes.length, 28);
        cd.writeUInt16LE(0,          30);
        cd.writeUInt16LE(0,          32);
        cd.writeUInt16LE(0,          34);
        cd.writeUInt16LE(0,          36);
        cd.writeUInt32LE(0,          38);
        cd.writeUInt32LE(offset,     42);
        nameBytes.copy(cd, 46);

        offset += lh.length + fileData.length;
        centralDir.push(cd);
      }
    }
  }

  walk(sourceDir, "");

  const cdBuf = Buffer.concat(centralDir);
  const eocd  = Buffer.alloc(22);
  eocd.writeUInt32LE(0x06054b50,        0);
  eocd.writeUInt16LE(0,                 4);
  eocd.writeUInt16LE(0,                 6);
  eocd.writeUInt16LE(centralDir.length, 8);
  eocd.writeUInt16LE(centralDir.length, 10);
  eocd.writeUInt32LE(cdBuf.length,      12);
  eocd.writeUInt32LE(offset,            16);
  eocd.writeUInt16LE(0,                 20);

  fs.writeFileSync(zipPath, Buffer.concat([...localBlocks, cdBuf, eocd]));
}

// ── Load .env ────────────────────────────────

function loadEnv() {
  const envPath = path.resolve(__dirname, ".env");
  if (!fs.existsSync(envPath)) {
    console.error("ERROR: .env file not found. Copy .env.example to .env and fill in values.");
    process.exit(1);
  }
  const lines = fs.readFileSync(envPath, "utf-8").split("\n");
  const env = {};
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIdx = trimmed.indexOf("=");
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const value = trimmed.slice(eqIdx + 1).trim();
    env[key] = value;
  }
  return env;
}

// ── Generate config.js ───────────────────────

function generateConfig(env) {
  const config = `// AUTO-GENERATED by build.js — do not edit manually
const ENV = Object.freeze({
  API_BASE_URL: "${env.API_BASE_URL || "https://price-tracker.gavaller.com/api/tesco"}",
  ALERTS_API_URL: "${env.ALERTS_API_URL || "https://price-tracker.gavaller.com/api/alerts"}",
  AUTH_GATEWAY_URL: "${env.AUTH_GATEWAY_URL || "https://gateway.gavaller.com"}",
  KEYCLOAK_URL: "${env.KEYCLOAK_URL || "https://auth.gavaller.com/realms/backend-ecosystem"}",
  KEYCLOAK_CLIENT_ID: "${env.KEYCLOAK_CLIENT_ID || "gateway-client"}",
  WEBSITE_URL: "${env.WEBSITE_URL || "https://price-tracker.gavaller.com"}",
});

export default ENV;
`;
  const configPath = path.resolve(__dirname, "env", "config.js");
  fs.writeFileSync(configPath, config, "utf-8");
  console.log("  ✓ env/config.js generated");
}

// ── Platform manifest generation ─────────────

function generateManifest(platform, env) {
  const base = JSON.parse(fs.readFileSync(path.resolve(__dirname, "manifest.json"), "utf-8"));

  if (platform === "firefox") {
    // Firefox uses browser_specific_settings
    base.browser_specific_settings = {
      gecko: {
        id: env.FIREFOX_EXTENSION_ID || "tesco-price-tracker@example.com",
        strict_min_version: "112.0",
      },
    };
    // Firefox MV3 uses "scripts" array for background
    base.background = { scripts: ["background/background.js"], type: "module" };
  } else {
    // Chrome / Edge use service_worker
    delete base.browser_specific_settings;
    base.background = { service_worker: "background/background.js", type: "module" };
  }

  return base;
}

// ── Package into .zip ────────────────────────

function buildPlatform(platform, env) {
  console.log(`\n── Building for ${platform.toUpperCase()} ──`);

  const distDir = path.resolve(__dirname, "dist", platform);
  if (fs.existsSync(distDir)) {
    fs.rmSync(distDir, { recursive: true });
  }
  fs.mkdirSync(distDir, { recursive: true });

  // Files/dirs to copy
  const items = [
    "env",
    "background",
    "content",
    "popup",
    "icons",
  ];

  for (const item of items) {
    const src = path.resolve(__dirname, item);
    const dest = path.resolve(distDir, item);
    if (fs.existsSync(src)) {
      copyRecursive(src, dest);
    }
  }

  // Generate platform-specific manifest
  const manifest = generateManifest(platform, env);
  fs.writeFileSync(path.resolve(distDir, "manifest.json"), JSON.stringify(manifest, null, 2));
  console.log(`  ✓ manifest.json (${platform})`);

  // Create .zip with forward-slash entry paths (required by Firefox / ZIP spec)
  const zipName = `tesco-price-tracker-${platform}.zip`;
  const zipPath = path.resolve(__dirname, "dist", zipName);
  if (fs.existsSync(zipPath)) fs.unlinkSync(zipPath);

  createZip(distDir, zipPath);
  console.log(`  ✓ ${zipName}`);
}

// ── Helpers ──────────────────────────────────

function copyRecursive(src, dest) {
  const stat = fs.statSync(src);
  if (stat.isDirectory()) {
    fs.mkdirSync(dest, { recursive: true });
    for (const child of fs.readdirSync(src)) {
      copyRecursive(path.join(src, child), path.join(dest, child));
    }
  } else {
    fs.copyFileSync(src, dest);
  }
}

// ── Main ─────────────────────────────────────

function main() {
  const args = process.argv.slice(2);
  const platforms = args.length ? args : ["chrome", "edge", "firefox"];

  console.log("Tesco Price Tracker — Extension Build");
  console.log("─".repeat(40));

  const env = loadEnv();
  generateConfig(env);

  for (const platform of platforms) {
    if (!["chrome", "edge", "firefox"].includes(platform)) {
      console.warn(`  ⚠ Unknown platform: ${platform}, skipping`);
      continue;
    }
    buildPlatform(platform, env);
  }

  console.log("\n✓ Build complete!");
  console.log(`  Output: ${path.resolve(__dirname, "dist")}`);
}

main();
