// AUTO-GENERATED by build.js — do not edit manually
const ENV = Object.freeze({
  API_BASE_URL: "https://price-tracker.gavaller.com/api/tesco",
  ALERTS_API_URL: "https://price-tracker.gavaller.com/api/alerts",
  AUTH_GATEWAY_URL: "https://price-tracker.gavaller.com/auth",
  KEYCLOAK_URL: "https://price-tracker.gavaller.com/kc/realms/tesco-tracker",
  KEYCLOAK_CLIENT_ID: "tesco-frontend",
  WEBSITE_URL: "https://price-tracker.gavaller.com",
});

export default ENV;
